version: "3"
services:
  frontend:
    build: ./frontend
    container_name: react-client
    restart: always

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
